org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
minecraft_version=1.20.1
forge_version=47.4.20
maven_group=com.yuan.live2d
archives_base_name=yuan_live2d
mod_version=1.0.0
cubism_sdk_archive=D:/mcmodwork/hackerwork/live2d-sdk/downloads/CubismSdkForNative-5-r.5.zip
cubism_sdk_sha256=ED2738ABF38141EE3609621D82600AF2F507167D6AB220401FF2015ABE5DCCF6
glew_archive=D:/mcmodwork/hackerwork/live2d-sdk/downloads/glew-2.2.0.zip
glew_sha256=A9046A913774395A095EDCC0B0AC2D81C3AACCA61787B39839B941E9BE14E0D4
